### ISSUE TITLE
Fix the daylight saving time issue

### ISSUE THREAD

**Issue by itsmais** [itsmais/world-clock#1]
Since the changing of daylight saving time, times in many cities (including Berlin and NYC) have been incorrect.

**Comment by fuadop** [comment]
Can you please explain the issue more?

**Comment by itsmais** [comment]
Hello Fuad!

If I look at time in Berlin now, it says 22:58:5, when it should be 21:58:5. 
So, having the UTC offsets statically saved in a list is not helpful during this half of the year since Berlin had +2 time offset and now it is +1. 
"On the first Sunday in November, at 2:00 a.m. EDT, clocks are moved back to 1:00 a.m. EST, thus "duplicating" one hour." from [Wikipedia](https://en.wikipedia.org/wiki/Eastern_Time_Zone#:~:text=In%20the%20northern%20parts%20of,thus%20%22duplicating%22%20one%20hour.).

So, as solutions, I can think of two:
- making 12 API requests to get the time for each city.
- checking what part of the year we are in, and having two offsets accordingly. i.e. an offset list for the time before 1st of Nov where Berlin is +2, and a second one (that's +1) for after that date.

Do you have any other solutions in mind? Also, is the issue clearer now?
